### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by adivine1199** [ryant18/Vim-Quickstart#1]
Consider adding more background information on the coding language. You do introduce it, but it might be helpful to add more information for those in CS that may be a little less familiar. Consider even adding when/who created it.

**Comment by ryant18** [comment]
Some other people have suggested this. At first I thought I would include a section about this, but as I was searching through git repos for other classes, I realized that this kind of information would not be useful. When people are searching for something, they are searching for that specific thing. So I expect people to come to this repo specifically looking for how to use Vim. When they have the goal of figuring out how to use Vim, putting the history or background would get in the way and be another thing they have to scroll past. If someone wants to know the history, then they can go on wikipedia. And for the non cs, I can't recommend that they use vim as it's not really designed for that use, so I don't think I should encourage them to do so.
