### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by adivine1199** [ryant18/Vim-Quickstart#3]
Consider adding additional sentences/information to the "Basic Usage" section. It stands out because it is so much shorter than all the other headings.

**Comment by ryant18** [comment]
Basic Usage was supposed to just be a main header to group everything below it. But there are some small things that are really important but don't have enough depth to be their own section. So I figured I could just shove it under that header. 
Now that I'm looking over it, maybe it's good that it sticks out as it seems that the smaller the section, the more important the information is.
