### ISSUE TITLE
basic usage section

### ISSUE THREAD

**Issue by Yusuf422** [ryant18/Vim-Quickstart#4]
I feel like this section is a little sparse, when it should be one of the longer ones because of how general "basic usage" is.  I would consider adding more information on the purpose of command text line editors and what makes Vim unique compared to nano or emacs.

**Comment by ryant18** [comment]
For adding more background, my answer for that is in #1 .
I don't want to really have any long sections. Ideally because it is so general I can move the information into subtopics instead of just under the main heading.
