### ISSUE TITLE
referring to other sections

### ISSUE THREAD

**Issue by Yusuf422** [ryant18/Vim-Quickstart#6]
Instead of describing relevant info once and linking to it throughout the document, I would just reiterate some of it.  For example, when you say that the difference between different versions will be found in the "advanced commands" section, I would just include the differences in both sections.  That might be awkward but I'd consider trying it out.

**Comment by ryant18** [comment]
I've removed the differences between the 2 versions in 20780b6e855d5efc1ca43d42af303b4092d9d5c0 as I found a work around for the permissions issue I was having. So I no longer need to have the section you are talking about. 
But I prefer to have it references all point to 1 place as it makes it easier to skip over the information if you are not interested in it or if you don't think it's relevant to what you are trying to do.
